-- 创建数据库表
CREATE TABLE IF NOT EXISTS hanzi (
  id INT AUTO_INCREMENT PRIMARY KEY,
  hanzi_name CHAR(1) NOT NULL,
  frequency DECIMAL(5,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS user (
  uid INT AUTO_INCREMENT PRIMARY KEY,
  frequency_level INT NOT NULL DEFAULT 1,
  create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_hanzi (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  hanzi_id INT NOT NULL,
  hanzi_name CHAR(1) NOT NULL,
  frequency DECIMAL(5,2) NOT NULL,
  sem_dom INT DEFAULT 0,
  pro_dom INT DEFAULT 0,
  learn_count INT DEFAULT 0,
  start_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
); 